// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsVFb3CxJqwNgY2EYrlkcDRFvjvEdtRCM',
    appId: '1:233663983604:web:e33c87e2d36e9a1ebe53a1',
    messagingSenderId: '233663983604',
    projectId: 'intern-7c1b9',
    authDomain: 'intern-7c1b9.firebaseapp.com',
    databaseURL: 'https://intern-7c1b9-default-rtdb.firebaseio.com',
    storageBucket: 'intern-7c1b9.appspot.com',
    measurementId: 'G-T1HY5M9R20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC38w5CzS9V0xEOf266twl_RBAEqwN79Jw',
    appId: '1:233663983604:android:7648a8f080c4cc9dbe53a1',
    messagingSenderId: '233663983604',
    projectId: 'intern-7c1b9',
    databaseURL: 'https://intern-7c1b9-default-rtdb.firebaseio.com',
    storageBucket: 'intern-7c1b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdWD18x6_XIL5GSmU1MmQTVnipsF4O1Bc',
    appId: '1:233663983604:ios:08d062fe2c3bde0ebe53a1',
    messagingSenderId: '233663983604',
    projectId: 'intern-7c1b9',
    databaseURL: 'https://intern-7c1b9-default-rtdb.firebaseio.com',
    storageBucket: 'intern-7c1b9.appspot.com',
    iosBundleId: 'com.example.demoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdWD18x6_XIL5GSmU1MmQTVnipsF4O1Bc',
    appId: '1:233663983604:ios:08d062fe2c3bde0ebe53a1',
    messagingSenderId: '233663983604',
    projectId: 'intern-7c1b9',
    databaseURL: 'https://intern-7c1b9-default-rtdb.firebaseio.com',
    storageBucket: 'intern-7c1b9.appspot.com',
    iosBundleId: 'com.example.demoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsVFb3CxJqwNgY2EYrlkcDRFvjvEdtRCM',
    appId: '1:233663983604:web:9617de77c768c09bbe53a1',
    messagingSenderId: '233663983604',
    projectId: 'intern-7c1b9',
    authDomain: 'intern-7c1b9.firebaseapp.com',
    databaseURL: 'https://intern-7c1b9-default-rtdb.firebaseio.com',
    storageBucket: 'intern-7c1b9.appspot.com',
    measurementId: 'G-Z0P490GFRN',
  );
}
